document.addEventListener('DOMContentLoaded', function() {
    const cardHTMl = document.getElementById('cardHTML');
    const cardCSS = document.getElementById('cardCSS');
    const cardBootstrap = document.getElementById('cardBootstrap');
    const cardJS = document.getElementById('cardJavaScript');
    const cardTS = document.getElementById('cardTS');
    const cardSQL = document.getElementById('cardSQL');
    const cardMySQL = document.getElementById('cardMySQL');
    const cardPostgreSQL = document.getElementById('cardPostgreSQL');
    const cardPython = document.getElementById('cardPython');
    const cardCPlus = document.getElementById('cardCPlus');
    const cardGoogle = document.getElementById('cardGoogle');
    const cardMicrosoft = document.getElementById('cardMicrosoft');
    const cardDatabase = document.getElementById('cardDataBase');
    const cardFrontEnd = document.getElementById('cardFrontEnd');
    const cardReact = document.getElementById('cardReact');
    const cardAngular = document.getElementById('cardAngular');
    const cardCrypto = document.getElementById('cardCrypto');
    const cardWeb = document.getElementById('cardWebDevelopment');
    const cardCybersecurity = document.getElementById('cardCybersecurity');
    const cardOther = document.getElementById('cardOther');

    const certificateHTML = document.getElementById('certificate-HTML');
    const certificateCSS = document.getElementById('certificate-CSS');
    const certificateBootstrap = document.getElementById('certificate-Bootstrap');
    const certificateJS = document.getElementById('certificate-JS');
    const certificateTS = document.getElementById('certificate-TS');
    const certificateSQL = document.getElementById('certificate-SQL');
    const certificateMySQL = document.getElementById('certificate-MySQL');
    const certificatePostgreSQL = document.getElementById('certificate-PostgreSQL');
    const certificatePython = document.getElementById('certificate-Python');
    const certificateCPlus = document.getElementById('certificate-CPlus');
    const certificateGoogle = document.getElementById('certificate-Google');
    const certificateMicrosoft = document.getElementById('certificate-Microsoft');
    const certificateDatabase = document.getElementById('certificate-DataBase');
    const certificateFrontEnd = document.getElementById('certificate-FrontEnd');
    const certificateReact = document.getElementById('certificate-React');
    const certificateAngular = document.getElementById('certificate-Angular');
    const certificateWeb = document.getElementById('certificate-Web');
    const certificateCrypto = document.getElementById('certificate-Crypto');
    const certificateCybersecurity = document.getElementById('certificate-Cubersecurity');
    const certificateOther = document.getElementById('certificate-Other');



    certificateHTML.style.display = 'none';
    certificateCSS.style.display = 'none';
    certificateBootstrap.style.display = 'none';
    certificateJS.style.display = 'none';
    certificateTS.style.display = 'none';
    certificateSQL.style.display = 'none';
    certificateMySQL.style.display = 'none';
    certificatePostgreSQL.style.display = 'none';
    certificatePython.style.display = 'none';
    certificateCPlus.style.display = 'none';
    certificateGoogle.style.display = 'none';
    certificateMicrosoft.style.display = 'none';
    certificateDatabase.style.display = 'none';
    certificateFrontEnd.style.display = 'none';
    certificateReact.style.display = 'none';
    certificateAngular.style.display = 'none';
    certificateWeb.style.display = 'none';
    certificateCrypto.style.display = 'none';
    certificateCybersecurity.style.display = 'none';
    certificateOther.style.display = 'none';

    cardHTMl.addEventListener('click', function() {
        certificateHTML.style.display = 'flex';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardCSS.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'flex';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardBootstrap.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'flex';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardJS.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'flex';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardTS.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'flex';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardSQL.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'flex';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardMySQL.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'flex';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardPostgreSQL.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'flex';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardPython.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'flex';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardCPlus.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'flex';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardGoogle.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'flex';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardMicrosoft.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'flex';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardDatabase.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'flex';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardFrontEnd.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'flex';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardReact.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'flex';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardAngular.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'flex';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardWeb.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'flex';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardCrypto.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'flex';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'none';
    });

    cardCybersecurity.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'flex';
        certificateOther.style.display = 'none';
    });

    cardOther.addEventListener('click', function() {
        certificateHTML.style.display = 'none';
        certificateCSS.style.display = 'none';
        certificateBootstrap.style.display = 'none';
        certificateJS.style.display = 'none';
        certificateTS.style.display = 'none';
        certificateSQL.style.display = 'none';
        certificateMySQL.style.display = 'none';
        certificatePostgreSQL.style.display = 'none';
        certificatePython.style.display = 'none';
        certificateCPlus.style.display = 'none';
        certificateGoogle.style.display = 'none';
        certificateMicrosoft.style.display = 'none';
        certificateDatabase.style.display = 'none';
        certificateFrontEnd.style.display = 'none';
        certificateReact.style.display = 'none';
        certificateAngular.style.display = 'none';
        certificateWeb.style.display = 'none';
        certificateCrypto.style.display = 'none';
        certificateCybersecurity.style.display = 'none';
        certificateOther.style.display = 'flex';
    });
});